name: Build site

on:
  push:
    branches: [ master ]

env:
  PUB_BRANCH: publish

jobs:
  run-build-script:
    name: Build Site
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH Keys and known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts && \
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null && \
          echo "got here" && \
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}" && \
          echo "all done"

      - name: Build submodules
        run: ./.github/scripts/compile-repository.sh

      - name: Make root head directory
        run: |
          find . -maxdepth 1 -mindepth 1 -not \( -path ./.git -o -path ./root \) -exec rm -r {} \;
          mv ./root/* ./
          rm -r root
          git add .
          git commit -m ":building_construction: Make root main directory"
          git push