# This is a basic workflow to help you get started with Actions

name: Compile Website

on:
  push:
    branches: [ compile-submodules ]

env:
  PUB_BRANCH: publish

jobs:
  compile-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile site
        run: ./.github/scripts/compile-site.sh