# This is a basic workflow to help you get started with Actions

name: Compile Website

on:
  push:
    branches: [ master ]

env:
  PUB_BRANCH: publish

jobs:

  compile-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Compile site
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch -f $PUB_BRANCH
          git checkout $PUB_BRANCH

          find . \( -type d -name node_modules \) -prune -false -o \
          -type f \( -name ".gitignore" -o -name "*.md" -o -name ".gitmodules" -o -path "./*/*.git" \) -exec git rm {} \;
          git commit -m ":fire: Remove unnecessary files"
          
          npm run compile-site
          git rm -r node_modules package.json package-lock.json
          git add .
          git commit -m ':rocket: Compile Site'

          git push -uf origin $PUB_BRANCH