# This is a basic workflow to help you get started with Actions

name: Compile Website

on:
  push:
    branches: [ compile-submodules ]

env:
  PUB_BRANCH: publish

jobs:
  compile-site:
    runs-on: ubuntu-latest
    env:
      PUSH_AUTH: ${{ secrets.PUSH_AUTH }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Compile site
        run: ./.github/scripts/compile-site.sh