# This is a basic workflow to help you get started with Actions

name: Compile Website

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Create new branch (publish)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch -f publish
          git checkout publish
          git rm .gitignore
          git commit -m "Remove .gitignore"
          git push -uf origin publish


  compile-sass:
    runs-on: ubuntu-latest
    needs: [create-branch]
    steps:
      - name: Checkout publish branch
        uses: actions/checkout@v2
        with:
          ref: publish

      - name: Find sass files & create .css paths
        run: ./.github/scripts/find-scss.sh

      - name: Compile .css from .scss files
        if: ${{ env.sources != '' }}
        uses: bkeys818/sass-build@master
        with:
          source: |
            ${{env.sources}}
          destination: |
            ${{env.destinations}}

      - name: Remove .scss files and push changes
        if: ${{ env.sources!= '' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git rm *.scss
          git commit -m "Compile sass"
          git push


  compile-ts:
    runs-on: ubuntu-latest
    needs: [create-branch, compile-sass]
    steps:
      - name: Checkout publish branch
        uses: actions/checkout@v2
        with:
          ref: publish

      - name: Find TypeScript files
        run: |
          ts_files=$(./.github/scripts/search-files.sh "-name *.ts")
          echo "ts_files<<{delimiter}
          ${ts_files}
          {delimiter}" >> $GITHUB_ENV

      - name: Compile TypeScript
        if: ${{ env.ts_files != '' }}
        run: |
          for file in $ts_files; do
            tsc $file;
          done;

      - name: Configure git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit changes
        if: ${{ env.ts_files != '' }}
        run: |
          git add .
          git rm *.ts
          git commit -m "Compile typescript"
          
      - name: Push changes
        run: git push
