# This is a basic workflow to help you get started with Actions

name: Compile Website

on:
  push:
    branches: [ rebuild-worflow ]
  workflow_dispatch:


env:
  PUB_BRANCH: publish


jobs:

  find-files:
    runs-on: ubuntu-latest
    outputs:
      sass_files: ${{ steps.find-files.outputs.sass_files }}
      ts_files: ${{ steps.find-files.outputs.ts_files }}
      js_files: ${{ steps.find-files.outputs.js_files }}
      html_files: ${{ steps.find-files.outputs.html_files }}
      svg_files: ${{ steps.find-files.outputs.svg_files }}
    env:
      ignore: |
        ./github
    steps:
      - uses: actions/checkout@v2
      - id: find-files
        run: ./.github/scripts/find-files.sh
      - name: Create new branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch -f $PUB_BRANCH


  compile-sass:
    runs-on: ubuntu-latest
    needs: find-files
    env: 
      sources:
      destinations:
    
    steps:
#       - name: Checkout new branch
#         if: $${{ needs.find-files.outputs.sass_files }}
        - uses: actions/checkout@v2
          with:
            ref: ${{env.PUB_BRANCH}}

        - name: Test
          if: $${{ needs.find-files.outputs.sass_files != null }}
          run: echo "\"${{ needs.find-files.outputs.sass_files }}\""


#       - name: Find sass files & create .css paths
#         if: $${{ needs.find-files.outputs.sass_files }}
#         run: |
#           lb=$'\n';
#           export IFS=":";
#           for file in $sass_files; do
#               sources+="$file$lb";
#               destinations+="${file%????}css$lb";
#           done;
#           echo "sources<<{delimiter}
#           ${sources%?}
#           {delimiter}" >> $GITHUB_ENV
#           echo "destinations<<{delimiter}
#           ${destinations%?}
#           {delimiter}" >> $GITHUB_ENV

#       - name: Compile .css from .scss files
#         if: $${{ needs.find-files.outputs.sass_files }}
#         uses: bkeys818/sass-build@master
#         with:
#           source: |
#             ${{env.sources}}
#           destination: |
#             ${{env.destinations}}

#       - name: Remove .scss files and push changes
#         if: $${{ needs.find-files.outputs.sass_files }}
#         run: |
#           git config user.name github-actions
#           git config user.email github-actions@github.com
#           git add .
#           git rm *.scss
#           git ls-files
# # git commit -m "Compile sass"