# This is a basic workflow to help you get started with Actions

name: Compile Website

on:
  push:
    branches: [ rebuild-worflow ]
  workflow_dispatch:


env:
  PUB_BRANCH: publish


jobs:

  find-files:
    runs-on: ubuntu-latest
    outputs:
      sass_files: ${{ steps.find-files.outputs.sass_files }}
      ts_files: ${{ steps.find-files.outputs.ts_files }}
      js_files: ${{ steps.find-files.outputs.js_files }}
      html_files: ${{ steps.find-files.outputs.html_files }}
      svg_files: ${{ steps.find-files.outputs.svg_files }}
    env:
      ignore: |
        ./github
    steps:
      - uses: actions/checkout@v2

      - name: Find files
        run: ./.github/scripts/find-files.sh

      - name: Create new branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch -f $PUB_BRANCH

      - name: Compile Sass 
        if: ${{ hashFiles('**/*.sass', '!**_*/*.sass', '**/*.scss', '!**/_*.scss', '!**/.github/**', '!**/node_modules/**') }}
        run: echo "Contains Sass"

      - name: Compile Typescript
        if: ${{ hashFiles('**/*.ts', !**/.github/**', '!**/node_modules/**') }}
        run: echo "\"$ts_files\""

      - name: Minify Javascript
        if: ${{ hashFiles('**/*.js', !**/.github/**', '!**/node_modules/**') }}
        run: echo "\"$js_files\""

      - name: Minify HTML
        if: ${{ hashFiles('**/*.html', !**/.github/**', '!**/node_modules/**') }}
        run: echo "\"$html_files\""

      - name: Minify SVG
        if: ${{ hashFiles('**/*.svg', !**/.github/**', '!**/node_modules/**') }}
        run: echo "\"$svg_files\""